services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    volumes:
      - minio_data:/data

  app:
    build: .
    depends_on:
      - minio
    environment:
      # S3 / MinIO
      S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio12345
      AWS_DEFAULT_REGION: us-east-1
      BRONZE_BUCKET: lake-bronze
      SILVER_BUCKET: lake-silver
      GOLD_BUCKET: lake-gold
      # Prefect always-on (Server + Worker)
      PREFECT_HOST: 0.0.0.0
      PREFECT_PORT: "4200"
      WORK_POOL: default
      WORKER_NAME: app-worker
      PREFECT_LOGGING_LEVEL: INFO
    ports:
      - "4200:4200"   # Prefect UI

volumes:
  minio_data:
